# Generated by Django 5.2.5 on 2025-08-22 19:39

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_seat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="geom",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326, verbose_name="Ubicación"
            ),
        ),
    ]
