# Generated by Django 5.2.5 on 2025-08-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_seat", "0002_venue_geom"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name="venue",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
