# Generated by Django 5.2.5 on 2025-08-22 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_seat", "0003_venue_latitude_venue_longitude"),
    ]

    operations = [
        migrations.RemoveField(model_name="venue", name="geom",),
    ]
