# Generated by Django 5.2.5 on 2025-08-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seat', '0004_remove_venue_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
