# Generated by Django 5.2.5 on 2025-08-26 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seat', '0005_section_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['venue', 'order', 'name'], 'verbose_name_plural': 'Sections'},
        ),
        migrations.RemoveField(
            model_name='section',
            name='sort_order',
        ),
    ]
