# Generated by Django 5.2.5 on 2025-08-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seat', '0006_alter_section_options_remove_section_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='row',
            name='order',
            field=models.IntegerField(default=1, verbose_name='Orden'),
        ),
    ]
