# Generated by Django 5.2.5 on 2025-09-25 21:19

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_seat', '0007_alter_row_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Ubicación'),
        ),
    ]
