# Generated by Django 5.2.5 on 2025-08-20 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app_core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="admincolumnpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AddIndex(
            model_name="translation",
            index=models.Index(
                fields=["model", "object_id", "field", "language"],
                name="app_core_tr_model_9c5540_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="translation",
            unique_together={("model", "object_id", "field", "language")},
        ),
        migrations.AlterUniqueTogether(
            name="admincolumnpreference", unique_together={("user", "model_name")},
        ),
    ]
