# Generated by Django 5.2.5 on 2025-08-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='model',
            field=models.CharField(choices='[]', max_length=50, verbose_name='Modelo'),
        ),
    ]
