# Generated by Django 5.2.5 on 2025-08-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_core", "0005_alter_translation_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="model",
            field=models.CharField(choices="[]", max_length=50, verbose_name="Modelo"),
        ),
    ]
