# Generated by Django 5.2.5 on 2025-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0008_alter_translation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translation',
            name='model',
            field=models.CharField(choices="[('AdminColumnPreference', 'AdminColumnPreference'), ('Translation', 'Translation')]", max_length=50, verbose_name='Modelo'),
        ),
    ]
