# Generated by Django 5.2.5 on 2025-08-21 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_security', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitypolicy',
            options={'default_permissions': (), 'permissions': (('require_2fa', 'Require Two-Factor Authentication'),)},
        ),
    ]
